config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # criar rotas pros nossos métodos
  resources :users, only: [:index, :create]

  resources :weapons, only: [:index, :create, :destroy, :show]

  resources :enemies, only: [:index, :create, :update, :destroy, :show]

  # criar rota para a página inicial
  root 'weapons#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enemy.rb
# Gerar model
# rails g model enemy name:string power_base:integer power_step:integer level:integer kind:integer

class Enemy < ApplicationRecord
  enum kind: [ :goblin, :orc, :demon, :dragon ]
  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }
  validates_presence_of :name, :power_base, :power_step, :level, :kind

  def current_power
    power_base + (power_step * (level - 1))
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum kind: [ :knight, :wizard ]
  # validações
  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

  # método customizado
  def title
    "#{self.kind} #{self.nickname} ##{self.level}"
  end
end

app/models/weapon.rb
# - criar model
# rails generate model weapon

# - adicionar campos no model
# rails g migration add_name_description_level_powerbase_powerstep_to_weapon 
# name:string description:text power_base:integer power_step:integer level:integer

class Weapon < ApplicationRecord
  # ==== validações ====
  # level: começa em 1 e não tem restrição de máximo
  validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }

  # minha ideia - não pode deixar o usuário criar uma arma sem nome e sem descrição
  validates :name, :description, presence: true

  # power_base: começa em 3000
  validates :power_base, inclusion: { in: [3000, 6000, 9000] }

  # power_step: + 100 por level
  validates :power_step, numericality: { equal_to:100 }

  # ==== métodos ====
  # método que demonstra o poder atual da arma
  def current_power
    self.power_base + (self.power_step * (self.level - 1))
  end

  # método que mostra o título da arma
  def title
    "#{self.name} ##{self.level}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  before_action :set_enemy, only: [:show, :update, :destroy]

  # devolve todas as informações do inimigo via json
  def index
    @enemies = Enemy.all
  end

  # devolve todas as informações de um inimiigo específico via json (espciificado pelo id)
  def show
    @enemy
  end

  # cria um novo inimigo e devolve as informações dele via json
  def create
    @enemy = Enemy.new(enemy_params)  
    if @enemy.save
      render json: @enemy, status: :created, location: @enemy
    else
      render json: @enemy.errors, status: :unprocessable_entity
    end
  end

  def update
    if @enemy.update(enemy_params)
      render json: @enemy 
      # tinha "", status :ok", mas deu erro nos testes
      # mas como o status :ok é o padrão, então não precisa colocar
    else
      render json: { errors: @enemy.errors }, status: :unprocessable_entity # 422
    end
  end

  def destroy
    @enemy.destroy
    head 204 # ou :no_content => é o status de sucesso, mas sem conteúdo

    # OBS: se algo der errado, com o id incorreto, vai ser pego pelo rescue do set_enemy
  end

  private

  # aqui filtramos os parâmetros recebidos pela web, para não permitir que o usuário envie dados que não queremos
  def enemy_params
    params.permit(:name, :power_base, :power_step, :level, :kind)
  end

  def set_enemy
    @enemy = Enemy.find(params[:id])
  # o rescue captura o erro e não deixa travar a aplicação
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :not_found # 404
  end
end

app/controllers/users_controller.rb
# Criando um controller básico
# rails g controller users index create --no-helper --no-assets --no-controller-specs --no-view-specs --skip-routes

class UsersController < ApplicationController
  # lista todos os usuários
  def index
    @users = User.all
  end

  # permite a criação de um novo usuário
  def create
    @user = User.create(user_params)
    # redireciona para a página de usuários (index)
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :level, :kind)
  end
end

app/controllers/weapons_controller.rb
# rodei:
# rails g controller weapons index create --no-helper --no-assets --no-controller-specs --no-view-specs --skip-routes
# teria facilitado eu usar além de index e create, show, update e destroy

class WeaponsController < ApplicationController
  # set_weapon é um before_action: antes de executar quaisquer desses métodos, ele executa o set_weapon
  before_action :set_weapon, only: [:show, :update, :destroy]

  def index
    @weapons = Weapon.all
  end

  def create
    @weapon = Weapon.create(weapon_params)
    redirect_to weapons_path
  end

  # não sei se funciona
  def destroy
    @weapon.destroy
    redirect_to weapons_path
  end

  # devolve uma página com todos os detalhes de uma das armas
  # não sei se funciona
  def show
    @weapon
  end

  def update
    @weapon.update!(weapon_params)
  end

  private

  def set_weapon
    @weapon = Weapon.find(params[:id])
  end

  def weapon_params
    params.require(:weapon).permit(:name, :level, :power_base, :power_step, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/enemies/destroy.html.erb
<h1>Enemies#destroy</h1>
<p>Find me in app/views/enemies/destroy.html.erb</p>

app/views/enemies/index.html.erb
<h1>Enemies#index</h1>

<% @enemies.each do |enemy| %>
  <h1><%= enemy.name %></h1>
  <p><%= enemy.power_base %></p>
  <p><%= enemy.power_step %></p>
  <p><%= enemy.level %></p>
  <p><%= enemy.kind %></p>
  <p><%= enemy.current_power %></p>
  <%= link_to "Detalhes".html_safe, enemy %>
<% end %>

app/views/enemies/show.html.erb
<h1><%= @enemy.name %></h1>
<p><%= @enemy.power_base %></p>
<p><%= @enemy.power_step %></p>
<p><%= @enemy.level %></p>
<p><%= @enemy.kind %></p>
<p><%= @enemy.current_power %></p>

app/views/enemies/update.html.erb
<h1>Enemies#update</h1>
<p>Find me in app/views/enemies/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursoTestesRspecOnebitcode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>

<% @users.each do |user| %>
  <p>
    <%= user.title %>
  </p>
<% end %>

app/views/weapons/create.html.erb
<h1>Weapons#create</h1>
<p>Find me in app/views/weapons/create.html.erb</p>

<%= form_for @weapon do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/weapons/delete.html.erb
<h1>Weapons#delete</h1>
<p>Find me in app/views/weapons/delete.html.erb</p>

app/views/weapons/index.html.erb
<h1>Weapons#index</h1>
<hr/>

<h2>Cadastrar Arma</h2>
<%= form_for Weapon.new do |f| %>
    <div id="name-description">
        <p>
            <%= f.label :name %><br/>
            <%= f.select :name, options_for_select([ 'Escolha:', 'faca', 'machado', 'espada']) %>
        </p>
        <p>
            <%= f.label :description %><br/>
            <%= f.text_area :description %>
        </p>
    </div>

    <div id="labels">
        <p>
            <%= f.label :level %><br/>
            <%= f.select :level, options_for_select((1..99).to_a) %>
        </p>
        <p>
            <%= f.label :power_base %><br/>
            <%= f.select :power_base, options_for_select([3000, 6000, 9000]) %>
        </p>
        <p>
            <%= f.label :power_step %><br/>
            <%= f.select :power_step, options_for_select([100]) %>
        </p>
    </div><br/>

    <%= f.submit 'Criar Arma' %>
<% end %>

<h2>Armas Cadastradas</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Current-Power</th>
      <th>Power-Step</th>
      <th>Title</th>
      <th>Show</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @weapons.each_with_index do |weapon| %>
      <tr>
        <td><%= weapon.name %></td>
        <td><%= weapon.current_power %></td>
        <td><%= weapon.power_step %></td>
        <td><%= weapon.title %></td>
        <td><%= link_to "Detalhes".html_safe, weapon %></td>
        <td><%= link_to 'Deletar', weapon_path(weapon), method: :delete %></td> 
      </tr>
    <% end %>
  </tbody>
</table>
<style>
    body {
        width: 800px;
        margin: 0 auto;
    }
    h1 {
        margin-top: 30px;
    }
    form {
        background-color: gray;
        width: 600px;
        margin: 10px auto;
        padding: 0 20px 20px;
        border-radius: 10px;
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    #name-description, #labels {
        display: flex;
        gap: 30px;
    }
    select, input, textarea {
        width: 150px;
        padding: 5px;
        border-radius: 5px;
        background-color: white;
    }
    textarea {
        width: 250px;
        height: 70px;
    }
    table {
        border-collapse: collapse;
        padding: 10px;
        width: 700px;
        margin: 10px auto;
    }
    table, th, td {
        border: 1px solid black;
        text-align: center;
        padding: 5px 10px;
    }

</style>

app/views/weapons/show.html.erb
<h1><%= @weapon.name %></h1>
<p><%= @weapon.description %></p>
<p><%= @weapon.power_base %></p>
<p><%= @weapon.power_step %></p>
<p><%= @weapon.level %></p>
<p><%= @weapon.current_power %></p>
<p><%= @weapon.title %></p>